/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "体验至上",
  "description": "note",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "前端修炼",
        "tagline": "God helps those who help themselves.",
        "bgImageStyle": {
          "height": "450px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3a56fd94",
      "path": "/"
    },
    {
      "title": "Git在工作流程中的使用",
      "frontmatter": {
        "title": "Git在工作流程中的使用",
        "date": "2020-11-10T00:00:00.000Z",
        "tags": [
          "Git"
        ],
        "categories": [
          "前端工具"
        ]
      },
      "regularPath": "/pages/Git/gitwork.html",
      "relativePath": "pages/Git/gitwork.md",
      "key": "v-1b4c722b",
      "path": "/pages/Git/gitwork.html"
    },
    {
      "title": "second page in category1",
      "frontmatter": {
        "title": "second page in category1",
        "date": "2019-09-21T00:00:00.000Z",
        "tags": [
          "tag2"
        ],
        "categories": [
          "category1"
        ]
      },
      "regularPath": "/pages/category1/2019/092101.html",
      "relativePath": "pages/category1/2019/092101.md",
      "key": "v-3e26b7d0",
      "path": "/pages/category1/2019/092101.html"
    },
    {
      "title": "vuepress-theme-reco",
      "frontmatter": {
        "title": "vuepress-theme-reco",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/pages/other/guide.html",
      "relativePath": "pages/other/guide.md",
      "key": "v-1ee672ea",
      "path": "/pages/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ]
    },
    {
      "title": "second page in category20",
      "frontmatter": {
        "title": "second page in category20",
        "date": "2020-11-4",
        "tags": [
          "tag2"
        ],
        "categories": [
          "category1"
        ]
      },
      "regularPath": "/pages/category1/2020/101011.html",
      "relativePath": "pages/category1/2020/101011.md",
      "key": "v-a2f00010",
      "path": "/pages/category1/2020/101011.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Git Tags"
      },
      "regularPath": "/tag/Git/",
      "key": "v-32555732",
      "path": "/tag/Git/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag2 Tags"
      },
      "regularPath": "/tag/tag2/",
      "key": "v-1368f226",
      "path": "/tag/tag2/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端工具 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF%E5%B7%A5%E5%85%B7/",
      "key": "v-063ec886",
      "path": "/categories/前端工具/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "category1 Categories"
      },
      "regularPath": "/categories/category1/",
      "key": "v-5ce69b3a",
      "path": "/categories/category1/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "TimeLine",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/recoluan",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        "",
        "theme",
        "plugin",
        "api"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "friendLink": [
      {
        "title": "罗宇萌",
        "desc": "love u forever.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/logo.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "jianhao.han",
    "authorAvatar": "/cf9a3731eaa6e058be98d63314f10e2.jpg",
    "record": "xxxx",
    "startYear": "2017"
  }
}