/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Git": {
      "key": "Git",
      "scope": "tags",
      "path": "/tag/Git/",
      "pageKeys": [
        "v-1b4c722b"
      ]
    },
    "tag2": {
      "key": "tag2",
      "scope": "tags",
      "path": "/tag/tag2/",
      "pageKeys": [
        "v-3e26b7d0",
        "v-a2f00010"
      ]
    }
  },
  "categories": {
    "前端工具": {
      "key": "前端工具",
      "scope": "categories",
      "path": "/categories/前端工具/",
      "pageKeys": [
        "v-1b4c722b"
      ]
    },
    "category1": {
      "key": "category1",
      "scope": "categories",
      "path": "/categories/category1/",
      "pageKeys": [
        "v-3e26b7d0",
        "v-a2f00010"
      ]
    }
  },
  "timeline": {}
}