/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Git",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Git/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "tag2",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/tag2/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "前端工具",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端工具/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "category1",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/category1/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
}]